### ISSUE TITLE
保留”Group-ChangeIP“部分的未被DNS污染的域名，删除其他的

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#100]
ChangeIP(DNS仍然被污染的域名，其他均正常)：
changeip.net
cleansite.info
ddns.ms
dhcp.biz
esmtp.biz
fartit.com
freewww.biz
iownyour.org
itsaol.com
jetos.com
mrface.com
myddns.com
trickip.org
mymom.info
mypop3.org
myz.info
ns01.us
ns02.info
ns01.info
proxydns.com
onmypc.biz
pcanywhere.net

**Comment by Loukky** [comment]
重新整理了下,大部分仍然有http rst,其他的已处理
