### ISSUE TITLE
除A-Z（包括数字部分，但有少量测试）之外其他可能需要删除的域名

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#102]
删除解析不到（或已经关站）的域名：
adcex.com
bit-z.com
rightbtc.com
oex.com
localbitcoins.com
livecoin.net
kspcoin.com
bx.in.th
exx.com
etherdelta.com
bitinka.com.ar
dragonex.io
cointobe.com
coin2co.in
china-mmm.sa.com
allowed.org
aolchannels.aol.com
d1b183sg0nvnuh.cloudfront.net
d1c37gjwa26taa.cloudfront.net
d3rhr7kgmtrq1v.cloudfront.net
xxxy.biz
wha.la
myftp.name
sl-reverse.com
googlearth.com
googlelabs.com
gvt3.com
like.com
gov.taipei
10.tt
删除已恢复正常的域名：
bitcoinworld.com
btcbank.bank
coinex.com
xn--4gq171p.com
xn--oiq.cc（或无法确定？）
china-mmm.jp.net
tellme.pw
ninth.biz
ns01.info
dyndns.org
dyndns-pics.com
from-sd.com
from-pr.com
is-a-hunter.com
dynu.net
freeddns.org
facebook.design
facebook.net
rocksdb.org
agoogleaday.com
autodraw.com
chromeexperiments.com
creativelab5.com
deepmind.com
duck.com
getmdl.io
godoc.org
googlepagecreator.com
gwtproject.org
html5rocks.com
madewithcode.com
material.io
plus.codes
polymer-project.org
redhotlabs.com
shattered.io
web.dev
waveprotocol.org
x.company
naughtyamerica.com
nytlog.com(正常了，但变h网了？？？)
twitchcdn.net
usher.ttvnw.net
jtvnw.net
yahoo.co.jp(只有Search无法使用)
flurry.com(没被DNS污染，但是很慢)
0rz.tw
无法确定的域名：
topbtc.com
exrates.me
btctrade.im
c2cx.com
chaoex.com
amazon.co.jp（用自己的宽带（广东移动）能正常访问，站长工具测试50%被污染，疑似半墙？加上www全墙？）
bbc.co.uk（BBC能访问.....bbcchinese.com，bbc.in没被DNS污染，但会跳转bbc.co.uk）
javmoo.xyz（没有DNS污染，但访问艰难）
facebook.design(或恢复正常)
xn--ngstr-lra8j.com(解析不到IP，子域名也不给查询)
g-desktop.ruten(这个顶级域名好像不存在)
1-apple.com.tw

**Comment by Loukky** [comment]
http rst:
localbitcoins.com 
xn--4gq171p.com
tellme.pw
ns01.info
dyndns.org
dyndns-pics.com
from-sd.com
from-pr.com
is-a-hunter.com
dynu.net
freeddns.org
0rz.tw
bbc.co.uk
DNS污染:
dragonex.io
livecoin.net
d1b183sg0nvnuh.cloudfront.net
d1c37gjwa26taa.cloudfront.net
d3rhr7kgmtrq1v.cloudfront.net
c2cx.com
chaoex.com
javmoo.xyz
1-apple.com.tw
ip不通:
www.gov.taipei  
agoogleaday.com (Google CDN)

403,暂时不移除:
btcbank.bank
coinex.com

特别说明 :
gvt3.com 是谷歌一些服务的CDN域名.考虑到现在其子域名解析到国内,暂时把这个域名移除列表
ttvnw.net  是直播流媒体的CDN地址,做加速用
yahoo.co.jp 是考虑到雅虎ban掉了大陆IP,所以整个域名加进去的
flurry.com 同上
xn--ngstr-lra8j.com  谷歌play商店下载app时的地址,其80%解析到国外的,所以必须在列表中
**很多域名你用http访问的时候会被rst**

**Comment by hm9245** [comment]
> http rst: localbitcoins.com xn--4gq171p.com tellme.pw ns01.info dyndns.org dyndns-pics.com from-sd.com from-pr.com is-a-hunter.com dynu.net freeddns.org 0rz.tw bbc.co.uk DNS污染: dragonex.io livecoin.net d1b183sg0nvnuh.cloudfront.net d1c37gjwa26taa.cloudfront.net d3rhr7kgmtrq1v.cloudfront.net c2cx.com chaoex.com javmoo.xyz 1-apple.com.tw ip不通: [www.gov.taipei](http://www.gov.taipei) agoogleaday.com (Google CDN)
> 
> 403,暂时不移除: btcbank.bank coinex.com
> 
> 特别说明 : gvt3.com 是谷歌一些服务的CDN域名.考虑到现在其子域名解析到国内,暂时把这个域名移除列表 ttvnw.net 是直播流媒体的CDN地址,做加速用 yahoo.co.jp 是考虑到雅虎ban掉了大陆IP,所以整个域名加进去的 flurry.com 同上 xn--ngstr-lra8j.com 谷歌play商店下载app时的地址,其80%解析到国外的,所以必须在列表中 **很多域名你用http访问的时候会被rst**

感谢指正，接触过这些东西，就是域名太多测试不过来
