### ISSUE TITLE
一大堆正常网址（http协议+移动家宽）

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#104]
**已经将锁区网站排除掉了**
http://braze.com
http://hulu.com
http://mattwilcox.net
http://pximg.net
http://coinex.com
http://agoogleaday.com
http://deepmind.com
http://getmdl.io
http://chromium.org
http://godoc.org
http://chromestatus.com
http://creativelab5.com
http://igoogle.lv
http://igoogle.sk
http://autodraw.com
http://shattered.io
http://polymer-project.org
http://html5rocks.com
http://gwtproject.org
http://fragment.com
http://web.dev
http://www.gov.tw
http://data.gov.tw
http://hchcc.gov.tw
http://material.io
http://yimg.com
http://plus.codes
http://flurry.com
http://x.company
http://881903.com
http://matsucc.gov.tw
http://cdp.sinica.edu.tw
http://ait.org.tw
http://audionow.com
http://asacp.org
http://bitbucket.org
http://bt95.com
http://baywords.com
http://braumeister.org
http://cdbook.org
http://csuchen.de
http://codeskulptor.org
http://dollf.com
http://douhokanko.net
http://dayabook.com
http://dabr.co.uk
http://dupola.com
http://dropbooks.tv
http://e-gold.com
http://dotgov.gov
http://etvonline.hk
http://eu.org
http://fast.wistia.com
http://forums-free.com
http://foursquare.com
http://freechal.com
http://4sq.com
http://freewallpaper4.me
http://g-queen.com
http://github.io
http://grammaly.com
http://greenpeace.org
http://genuitec.com
http://graphql.org
http://hsjp.net
http://i818hk.com
http://idouga.com
http://iconpaper.org
http://imageshack.us
http://jackjia.com
http://ironpython.net
http://jigsy.com
http://kaiyuan.de
http://kcoolonline.com
http://letou.com
http://lkcn.net
http://meetup.com
http://my903.com
http://mthruf.com
http://nokogiri.org
http://oopsforum.com
http://omy.sg
http://pin6.com
http://blog.pentalogic.net
http://proxomitron.info
http://pureconcepts.net
http://qusi8.net
http://rainbowplan.org
http://quranexplorer.com
http://red-lang.org
http://relaxbbs.com
http://seevpn.com
http://sbs.com.au
http://shkspr.mobi
http://shvoong.com
http://sidelinessportseatery.com
http://smarthide.com
http://slinkset.com
http://slaytizle.com
http://soumo.info
http://smith.edu
http://stanford.edu
http://stepmania.com
http://cn.streetvoice.com
http://sugumiru18.com
http://surfeasy.com.au
http://thetinhat.com
http://twitterrific.com
http://vmixcore.com
http://vcf-online.org
http://lists.w3.org/archives/public
http://wheelockslatin.com
http://wikilivres.info
http://wikia.com
http://musical.ly
http://zlib.net
http://goliathguitartutorials.com
http://pornbest.org
http://electrek.co
http://dronedj.com
http://rocketcdn.me
http://docs.cfw.lbyczf.com
http://cloudflare.com
http://prosciana.com
http://hostloc.com
http://technews.tw
http://webpass.net
http://hcaptcha.com
http://ipinfo.io
http://tgfcer.com
http://githubmemory.com
http://gamme.com.tw
http://javfree.me
http://tvbs.com.tw
http://newrelic.com
http://truesocial.media
http://fontsource.org
http://tc39.es
http://roucdn.link
http://fast.com
http://truenas.com
http://yandex.com
http://musescore.com
http://sprite.page
http://ontrac.com
http://tronscan.org
http://cloudokyo.cloud
http://telegram-store.com
http://docker.com
http://docker.io
http://claude.ai
http://www1.american.edu
http://blip.tv
http://gitbooks.io
http://p16-tiktokcdn-com.akamaized.net
http://nationwide.com
http://atv-ps.amazon.com
http://rcam.target.com
http://netflix.com
http://costco.com
http://costco.com
http://carfax.com
http://counter.social
http://centauro.com.br
http://wizcrafts.net
http://nflxvideo.net
http://stacksocial.com
http://desipro.de
http://go141.com
http://nightlife141.com
http://thinkgeek.com
http://nordstrom.com
http://hautelook.com
http://btcbank.bank
http://kknews.cc
http://read01.com
http://abematv.akamaized.net
http://linear-abematv.akamaized.net
http://alternativeto.net
http://vod-abematv.akamaized.net
http://bettween.com
http://bl-doujinsouko.com
http://blogs.com
http://bloomfortune.com
http://cdw.com
http://corumcollege.com
http://duckmylife.com
http://electionsmeter.com
http://duckload.com
http://fanswong.com
http://download.syniumsoftware.com
http://heartyit.com
http://howtoforge.com
http://idsam.com
http://ismprofessional.net
http://laptoplockdown.com
http://liudejun.com
http://liberal.org.hk
http://lookpic.com
http://picacomiccn.com
http://photofocus.com
http://css.pixnet.in
http://poskotanews.com
http://sogrady.me
http://sciencemag.org
http://skybet.com
http://skyvegas.com
http://sndcdn.com
http://twittermail.com
http://vpnpronet.com
http://wikileaks.eu
http://zvereff.com
http://use.fontawesome.com
http://mtzfile.pw
http://cws.conviva.com
http://aolnews.com
http://authorizeddns.org
http://ddns.me.uk
https://cdn.ampproject.org/
http://redirector.gvt1.com
http://waveprotocol.org
http://pagead2.googlesyndication.com
http://redhotlabs.com
http://hsinchu-cc.gov.tw
http://ntsec.gov.tw
http://aculo.us
http://assets.bwbx.io
http://blog.excite.co.jp
http://falunasia.info
http://freeforums.org
http://ghut.org
http://clementine-player.org
http://justtristan.com
http://cdn.assets.lfpcontent.com
http://mobileways.de
http://moviefap.com
http://nalandabodhi.org
http://sorting-algorithms.com
http://stumbleupon.com
http://toptip.ca
http://vimeocdn.com
http://www.zfreet.com/post/usejump-browns.html
http://zfreet.com
http://zillionk.com
http://skimresources.com
http://openbase.com
http://wikiwiki.jp
http://blog.fizzik.com
http://spb.com
http://webworkerdaily.com
http://br.st
http://foxsub.com
http://gardennetworks.org
http://gigacircle.com
http://gzm.tv
http://gutteruncensored.com
http://proxypy.net
http://quantumbooter.net
http://torrenty.org
http://vidinfo.org
http://gitmemory.com
http://barnabu.co.uk
http://bfsh.hk
http://www.klip.me
http://hwayue.org.tw
http://multiply.com
http://naitik.net
http://proyectoclubes.com
http://natado.com
http://rushbee.com

**Comment by Loukky** [comment]
某些域名,根域名是正常访问的,但是其中有一些二级域名会污染或者rst...可能有部分这样的域名也从列表里面删除了

**Comment by hm9245** [comment]
> 某些域名,根域名是正常访问的,但是其中有一些二级域名会污染或者rst...可能有部分这样的域名也从列表里面删除了

这点的话gfwlist原作者好像也考虑到了，子域名只要有一个污染就会加通配符

**Comment by hm9245** [comment]
列表更新，把其他状态码的域名（不包括锁区网站）给加了进去，没有分类

**Comment by Loukky** [comment]
hulu.com 是流媒体,最好是走代理
pximg.net 子域名污染
coinex.com 403
agoogleaday.com CDN不通
881903.com rst
csuchen.de/bbs rst
eu.org  子域名移动会阻断
github.io 部分二级域名被污染
jackjia.com 二级域名 blog.jackjia.com DNS污染
rainbowplan.org 移动墙了
musical.ly 国内无解析
technews.tw 国内解析错误
javfree.me 干扰
tvbs.com.tw 子域名 rst
cloudokyo.cloud 子域名加速用
hub.docker.com DNS污染
claude.ai 403
gitbooks.io 有子域名被墙
hwayue.org.tw 有子域名 rst

你列出的表里面,有一些本来就有做直连的处理,有一些是注释掉的,还有一些是网站方屏蔽了大陆ip.
还有一些域名虽然没有被墙,但由于实际需要也在列表里面.
