### ISSUE TITLE
kgithub.com

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#106]
GitHub的镜像站，域名被污染了

**Comment by hm9245** [comment]
一号机场.com
某个机场官网，域名被污染

**Comment by Loukky** [comment]
https://help.kgithub.com/
kgithub.com已于2023年9月4日被墙，域名已更换为kkgithub.com

**Comment by Loukky** [comment]
另外机场的域名是添加不完的,所以一般都没有添加机场的域名

**Comment by hm9245** [comment]
> 另外机场的域名是添加不完的,所以一般都没有添加机场的域名

虽然，但还是建议添加进去，被墙的机场域名似乎很少
