### ISSUE TITLE
一些网站

### ISSUE THREAD

**Issue by fluffyfoxxo** [Loukky/gfwlist-by-loukky#109]
AI 相关：
huggingface.co
civitai.com

Carrd 的域名：
carrd.co
drr.ac
uwu.ai
crd.co
ju.mp

**Comment by Loukky** [comment]
drr.ac  这个域名全球解析到127.0.0.1,不是被墙了  其子域名 mist.drr.ac 正常打开
uwu.ai
crd.co
ju.mp    同上  
其他被墙的已添加
