### ISSUE TITLE
www.sapo.pt

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#112]

**Comment by Loukky** [comment]
这个似乎可以打开

**Comment by hm9245** [comment]
移动宽带就reset了

________________________________________
发件人: Loukky ***@***.***>
发送时间: 2023年10月29日 20:28
收件人: Loukky/gfwlist-by-loukky
抄送: haoming9245; Author
主题: Re: [Loukky/gfwlist-by-loukky] www.sapo.pt (Issue #112)

这个似乎可以打开

―

**Comment by Loukky** [comment]
强中强没办法,跟gfw无关

**Comment by hm9245** [comment]
> 强中强没办法,跟gfw无关

~~建议给移动墙中墙单独开个分支（~~
