### ISSUE TITLE
20.205.243.166

### ISSUE THREAD

**Issue by haoming9245** [Loukky/gfwlist-by-loukky#121]
github服务器的IP，国内Ping不通

**Comment by Loukky** [comment]
GitHub.com 已经在列表了

**Comment by haoming9245** [comment]
> GitHub.com 已经在列表了

这个我知道，我的意思是加入IP墙那

**Comment by Loukky** [comment]
> > GitHub.com 已经在列表了
> 
> 这个我知道，我的意思是加入IP墙那

这个IP还有其他业务需要用到直连吗。
比如telegram是靠IP来链接通讯的，所以应该加入列表。这个IP有类似的业务吗

**Comment by haoming9245** [comment]
> > > GitHub.com 已经在列表了
> > 
> > 
> > 这个我知道，我的意思是加入IP墙那
> 
> 这个IP还有其他业务需要用到直连吗。 比如telegram是靠IP来链接通讯的，所以应该加入列表。这个IP有类似的业务吗

不太清楚，有可能GitHub Mobile会用到，具体没测试过

**Comment by Loukky** [comment]
> > > > GitHub.com 已经在列表了
> > > 
> > > 
> > > 这个我知道，我的意思是加入IP墙那
> > 
> > 
> > 这个IP还有其他业务需要用到直连吗。 比如telegram是靠IP来链接通讯的，所以应该加入列表。这个IP有类似的业务吗
> 
> 不太清楚，有可能GitHub Mobile会用到，具体没测试过

这个IP现在已经解封了
