### ISSUE TITLE
一些网址

### ISSUE THREAD

**Issue by qwerttvv** [Loukky/gfwlist-by-loukky#122]
被屏蔽
av01.tv
go.dev
v2board.com
madou.club
av01.tv 
sehuatang.org
sehuatang.net

主动屏蔽
haiwaikan.com

大陆不能用copilot
sydney.bing.com
copilot.microsoft.com

**Comment by haoming9245** [comment]
go.dev 正常 
cc @Loukky

**Comment by Loukky** [comment]
copilot 这个没有添加.
go.dev 这个是Google anycast CDN,所以也没有添加.
