### ISSUE TITLE
考虑将nytstyle.com移除

### ISSUE THREAD

**Issue by haoming9245** [Loukky/gfwlist-by-loukky#123]
原因:该域名未解析到任何域名，可能纽约时报不使用了

**Comment by Loukky** [comment]
www.nytchina.com

**Comment by haoming9245** [comment]
nytcn.me
nyt.com
nytco.com
nyti.ms
nytimg.com

不使用:
nytstyle.com

**Comment by haoming9245** [comment]
nyti.ms
nytimg.com

不使用:
nytstyle.com

**Comment by haoming9245** [comment]
> > nyti.ms nytimg.com
> > 不使用: nytstyle.com
> 
> http://cn.nytstyle.com/ 试试这个能正常访问吗？

额，又漏检测一个,不能........
