### ISSUE TITLE
some domains

### ISSUE THREAD

**Issue by ptr7F** [Loukky/gfwlist-by-loukky#124]
Not accessible:
wallhaven.cc
sakura-paris.org

Sometimes inaccessible:
windowscentral.com

**Comment by haoming9245** [comment]
`windowscentral.com` is using Fastly cdn (Fastly cdn is access slow at Mainland China)
so it's normal
cc @Loukky

**Comment by haoming9245** [comment]
> windowscentral.com

You can search `199.232.198.114` at google and you can get a common result
![image](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/3cd905bd-0f4d-49fc-b9f5-47123e34460f)

**Comment by haoming9245** [comment]
> I am curious about how to determine the CDN service used by a website. I used proxy service software to inspect the connection information for accessing windowscentral.com, and it revealed the use of futurecdn.net in the network connections.

You can search `199.232.198.114` at google and you can get a common result
![image](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/3cd905bd-0f4d-49fc-b9f5-47123e34460f)
