### ISSUE TITLE
亚马逊地址规则的问题  ||s3*.amazonaws.com

### ISSUE THREAD

**Issue by qwerttvv** [Loukky/gfwlist-by-loukky#125]
s3-us-west-1.amazonaws.com
s3.amazonaws.com

https://s3-us-west-1.amazonaws.com
https://s3.amazonaws.com

通过国外代理服务器在本地打开的话就会请求AAAA，但是v6记录就没有，空的，不知道为啥会请求AAAA……
https://dig.ping.pe/s3.amazonaws.com:AAAA:8.8.8.8
https://dig.ping.pe/s3.amazonaws.com:A:8.8.8.8
https://dig.ping.pe/s3.amazonaws.com:A:223.5.5.5
然后你要是在国内直接打开，就会跳转到https://aws.amazon.com/cn/s3/
在国外服务器上curl -sSL https://s3.amazonaws.com 也是正常打开的

||s3*.amazonaws.com

这个规则是不是得改改啊，要不然不知道为啥就请求AAAA去了
我也是看见代理软件报错才发现的
s3-us-west-1.amazonaws.com:443 connect failed, error: dns resolve s3-us-west-1.amazonaws.com:443 error: no record found for Query { name: Name("s3-us-west-1.amazonaws.com."), query_type: AAAA, query_class: IN

为啥请求AAAA别问，我不明白……

**Comment by Loukky** [comment]
你使用的是哪个应用？

**Comment by Loukky** [comment]
规则列表是不应该会影响到DNS解析结果的，特别是代理服务器的DNS。所以很可能是其他因素再影响
