### ISSUE TITLE
提供四个已被DNS污染的域名：www.post852.com, www.hket.com, geo.mydati.com和qiangwaikan.com

### ISSUE THREAD

**Issue by Kithup2020** [Loukky/gfwlist-by-loukky#13]
四个域名均已被DNS污染，污染字段是：
*.post852.com
*.hket.com
*.geo.mydati.com
*qiangwaikan.com

其中qiangwaikan.com除了DNS污染，疑似还有证书封锁或者SNI阻断

**Comment by Loukky** [comment]
已添加
