### ISSUE TITLE
提交一个被GFW投毒污染了的域名bcp.crwdcntrl.net

### ISSUE THREAD

**Issue by Kithup2020** [Loukky/gfwlist-by-loukky#18]
bcp.crwdcntrl.net
被DNS投毒污染

![bcp crwdcntrl net](https://user-images.githubusercontent.com/64726691/82743756-4b313400-9da2-11ea-8f8f-c22072b55d8c.jpg)

**Comment by Loukky** [comment]
bcp.crwdcntrl.net 302到 www.lotame.com 不加没影响
