### ISSUE TITLE
store.steampowered.com国内无法访问

### ISSUE THREAD

**Issue by bocchi810** [Loukky/gfwlist-by-loukky#190]
其他子域比如api.steampowered.com是正常的

**Comment by Loukky** [comment]
当你访问store.steampowered.com时，steam会根据你的IP属地分配其视频的CDN。是cn IP的话会分配到国内CDN，是非cn IP的话是分配akamai。为了保证访问的体验。所以直接整个域名都走代理了。

**Comment by Loukky** [comment]
我记错了.这个网址我以前加过,情况就是我上面说的那样.
这个不算被墙吧,应该是偶尔有干扰.应该是某些akamai的ip被阻断了.
你确定要加到列表吗?

**Comment by bocchi810** [comment]
加吧，现在不是偶尔干扰了，而是彻底rst了

**Comment by Loukky** [comment]
我这里可以正常连接，暂时先观察观察
