### ISSUE TITLE
huigui.tw

### ISSUE THREAD

**Issue by bocchi810** [Loukky/gfwlist-by-loukky#203]
以及其对应的ip
15.197.142.173
3.33.152.147

**Comment by Loukky** [comment]
Ip 也加到列表？

**Comment by bocchi810** [comment]
> Ip 也加到列表？

想了一下，我觉得就加域名算了

**Comment by Loukky** [comment]
才发现这个域名什么内容都没有,就是跳转到 gov.cn

**Comment by bocchi810** [comment]
我知道，我觉得还是加进去吧

**Comment by Loukky** [comment]
我加了,但是我感觉毫无意义.....

**Comment by bocchi810** [comment]
加吧，虽然没有内容，不过这个域名挺有意义的
________________________________
发件人: Loukky ***@***.***>
发送时间: 星期日, 三月 24, 2024 9:20:19 下午
收件人: Loukky/gfwlist-by-loukky ***@***.***>
抄送: bocchi810 ***@***.***>; Author ***@***.***>
主题: Re: [Loukky/gfwlist-by-loukky] huigui.tw (Issue #203)


我加了,但是我感觉毫无意义.....

―
