### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Hywfred** [Loukky/gfwlist-by-loukky#21]
你好，请教一下 gfwlist 是如何生成的？自己怎样维护？
谢谢！

**Comment by Loukky** [comment]
base64 解码与编码就可以了。
至于写法，网上搜索下，很多。

**Comment by Hywfred** [comment]
> base64 解码与编码就可以了。
> 至于写法，网上搜索下，很多。

OK，多谢！

**Comment by Loukky** [comment]
NO RESPON
