### ISSUE TITLE
account.live.com（附图片）

### ISSUE THREAD

**Issue by bocchi810** [Loukky/gfwlist-by-loukky#219]
![屏幕截图 2024-05-02 220918](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/a320f088-d2a6-43c7-b385-9ac5d2929cfc)

**Comment by Loukky** [comment]
![https___account live com_多地区多线路HTTP测速](https://github.com/Loukky/gfwlist-by-loukky/assets/12481807/6b799106-5658-4ff3-8f72-69108c8f3213)
没有问题呀?

**Comment by bocchi810** [comment]
前几天测试国内是没法正常访问的
