### ISSUE TITLE
提交一个被DNS污染的域名 lala.im

### ISSUE THREAD

**Issue by Kithup2020** [Loukky/gfwlist-by-loukky#22]
*.lala.im
已被DNS污染

![lala im](https://user-images.githubusercontent.com/64726691/85719103-b2376500-b721-11ea-99c2-f2ca4b29110d.jpg)
![test lala im](https://user-images.githubusercontent.com/64726691/85719113-b4012880-b721-11ea-94d0-e41ebd126ca8.jpg)

**Comment by Loukky** [comment]
fixed
