### ISSUE TITLE
提交一些域名

### ISSUE THREAD

**Issue by fluffyfoxxo** [Loukky/gfwlist-by-loukky#25]
DNS 污染：
urbandictionary.com
knowyourmeme.com

9to5 系列，都阻断了：
9to5mac.com
9to5toys.com
9to5google.com
electrek.co
dronedj.com

维基基金会系列全部被封锁：
wikinews.org（原列表中只有中文的 zh.wikinews.org）
wikisource.org
wikibooks.org
wiktionary.org
wikiquote.org
wikivoyage.org
wikiversity.org
species.wikimedia.org
commons.wikimedia.org
incubator.wikimedia.org
meta.wikimedia.org
upload.wikimedia.org
phabricator.wikimedia.org
wikitech.wikimedia.org
w.wiki
www.mediawiki.org
www.wikidata.org

**Comment by Loukky** [comment]
维基系列都能正常打开，其他已添加。

**Comment by fluffyfoxxo** [comment]
> 维基系列都能正常打开，其他已添加。

使用 IPv6 可以打开除中文维基百科外的其他域名，但是 IPv4 全部被封锁

**Comment by Loukky** [comment]
> > 维基系列都能正常打开，其他已添加。
> 
> 使用 IPv6 可以打开除中文维基百科外的其他域名，但是 IPv4 全部被封锁

已添加。
