### ISSUE TITLE
ko-fi.com

### ISSUE THREAD

**Issue by bocchi810** [Loukky/gfwlist-by-loukky#274]

**Comment by Loukky** [comment]
这个能打开耶

**Comment by bocchi810** [comment]
![image](https://github.com/user-attachments/assets/8e27cf3d-3283-4d5e-9e37-3a7fe00fff4c)
![image](https://github.com/user-attachments/assets/4671003c-95ef-439f-a99c-8c64e9c6aafc)
实测会出现GitHub的那种半墙现象
