### ISSUE TITLE
路由上ssr-plus使用该list，安卓手机谷歌Play商店可以访问，但是无法下载应用

### ISSUE THREAD

**Issue by zhouzl7** [Loukky/gfwlist-by-loukky#29]
路由上ssr-plus使用该list，安卓手机谷歌Play商店可以访问，但是无法下载应用。

**Comment by Loukky** [comment]
有试过其他的列表可以正常下载吗？比如gfwlist
另外你的手机是否为国行，试试再路由器上面将 services.googleapis.cn 强制走代理试试

**Comment by zhouzl7** [comment]
> 有试过其他的列表可以正常下载吗？比如gfwlist
> 另外你的手机是否为国行，试试再路由器上面将 services.googleapis.cn 强制走代理试试

gfwlist也是一样不能下载。手机是华为的手机。将 services.googleapis.cn 强制走代理好像不能解决问题。我换成大陆白名单模式，就可以正常下载。

**Comment by Loukky** [comment]
那只有在你手机上面抓包看下下载的时候走的什么域名。
