### ISSUE TITLE
githubusercontent.com、githubassets.com和github.com疑似解封

### ISSUE THREAD

**Issue by bocchi810** [Loukky/gfwlist-by-loukky#299]
换成公共dns就能正常解析，疑似仅运营商污染
由于Fastly CDN特性导致会有半墙症状
github.com除了新疆地区之外半墙状态已经没有了

**Comment by bocchi810** [comment]
刚才试了一下，好像又不行了

**Comment by Loukky** [comment]
github会有tls不定时干扰，这个可以根据之前的行为是可以预见到的，所以即便现在可以正常访问，也不代表能一直正常的访问。
我将其加入到列表中就是为了保证访问的流畅性，才能最大限度的避免防火墙所带来的不稳定。另外gist是一直被墙的。这本身就表明了防火墙的态度。
