### ISSUE TITLE
可否加入 *.githubusercontent.com 

### ISSUE THREAD

**Issue by CNLouisLiu** [Loukky/gfwlist-by-loukky#3]

**Comment by Loukky** [comment]
目前的策略是 raw.githubusercontent.com 在列表里面。

**Comment by CNLouisLiu** [comment]
目前我测试 这一系列域名都被污染了,表现现象为 图片不显示，头像不显示

**Comment by Loukky** [comment]
http://ping.chinaz.com/avatars0.githubusercontent.com
头像或者图片资源的域名
你头像的地址：
https://avatars3.githubusercontent.com/u/35774374?s=88&u=5b914f5f21261020ee76a35b4da7193c18f44f2a&v=4
我这里测试正常。你再测试下？

**Comment by CNLouisLiu** [comment]
我的头像地址 我本地网络是超时状态😂

**Comment by Loukky** [comment]
> 我的头像地址 我本地网络是超时状态

更换不同的网络测试下能否正常打开。

**Comment by CNLouisLiu** [comment]
我这里只有联通的网络.电信没有测试过 移动没有测试过 4G 5G 宽带都是被污染的

**Comment by Loukky** [comment]
> 我这里只有联通的网络.电信没有测试过 移动没有测试过 4G 5G 宽带都是被污染的

我测试联通和电信都可以正常打开。而且多地区ping测试也没有发现劫持现象。

**Comment by luomoxu** [comment]
dns应该是没被污染 但是curl是不通的
