### ISSUE TITLE
建议提供转码后为js格式的pac

### ISSUE THREAD

**Issue by PilotXia** [Loukky/gfwlist-by-loukky#30]
ssr原生的pac.txt是js编写的，例如这个格式：https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac ，这里面除了域名的列举外还有一些函数；您的gfwlist经过base64转码后就都是域名，没有函数。两个内容复制出来后当pac.txt用好像都没什么问题，但是不知没有函数的话会有哪些影响？如果有的话，能否在未来提供js格式的gfwlist？感谢！

**Comment by Loukky** [comment]
可以谷歌相关工具将gfwlist转成pac文件
