### ISSUE TITLE
chatgpt.com根域名似乎不在列表中

### ISSUE THREAD

**Issue by HappyRespawnanchor** [Loukky/gfwlist-by-loukky#313]
ab.chatgpt.com这种是在的，但根似乎不在，一些场景下根域名也需要在里面，希望添加

**Comment by bocchi810** [comment]
![图片](https://github.com/user-attachments/assets/00502357-7d4a-44f7-bdae-b445a8fe6f5c)
chatgpt.com在，但加个ab.chatgpt.com有点多此一举

**Comment by bocchi810** [comment]
> 这些官方文档提到的域名都要放进去。
> 
> https://help.openai.com/en/articles/9247338-network-recommendations-for-chatgpt-errors-on-web-and-apps

有些不用吧

**Comment by Loukky** [comment]
如果只使用网页的话应该用不着这么多域名。不排除在app里面使用了其他的域名。
