### ISSUE TITLE
可否每次更新一下更新时间？

### ISSUE THREAD

**Issue by iaston** [Loukky/gfwlist-by-loukky#4]
更新时间一直显示的是2019年11月4日。

[AutoProxy 0.2.9]
! Checksum: mIShJtvB4UUaZ7ms+0fm4g
! Expires: 6h
! Title: GFWList4LL
! GFWList with EVERYTHING included
! Last Modified: **Mon, 04 Nov 2019 11:21:47 -0500**
!
! HomePage: https://github.com/Loukky/gfwlist-by-loukky
! License: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
!

**Comment by Loukky** [comment]
因为我每次的更新内容不多，而且是随时会更新，所以就没改过日期。主要是大部分使用的软件或插件都有自动更新功能。如果确实有需要的话，会考虑添加更新日期。

**Comment by iaston** [comment]
谢谢加日期，已经看到了。

主要是之前用的有些列表长期不维护了，我们使用的人也不知道，一直傻傻地还在用。所以加上日期后至少我们知道这个列表还在维护中。
