### ISSUE TITLE
https://use.fontawesome.com code.jquery.com

### ISSUE THREAD

**Issue by LGA1150** [Loukky/gfwlist-by-loukky#40]
端口被墙

**Comment by Loukky** [comment]
已添加 use.fontawesome.com
code.jquery.com 测试可以正常访问

**Comment by LGA1150** [comment]
https://code.jquery.com 又不行了
我用 17ce.com 试过，全国基本无法访问

**Comment by Loukky** [comment]
已添加 code.jquery.com
