### ISSUE TITLE
您好，请问可否增加“TED演讲”网站的相关规则

### ISSUE THREAD

**Issue by 1263478456** [Loukky/gfwlist-by-loukky#53]
您好，请问可否增加“TED演讲”网站的相关规则，万分感谢

**Comment by Loukky** [comment]
我测试可以正常打开

**Comment by 1263478456** [comment]
> 我测试可以正常打开

您好，我这边是网站确实可以打开，但是演讲视频打不开，加载速度很慢，但是如果使用clash做代理的速度是够的，但是这个gfw规则列表好像是没有把ted的cdn域名放进列表

**Comment by Loukky** [comment]
> > 我测试可以正常打开
> 
> 您好，我这边是网站确实可以打开，但是演讲视频打不开，加载速度很慢，但是如果使用clash做代理的速度是够的，但是这个gfw规则列表好像是没有把ted的cdn域名放进列表

因为ted本身就没有被墙，连接速度慢是因为国内运营商出口原因。可以手动设置分流。

**Comment by 1263478456** [comment]
> > > 我测试可以正常打开
> > 
> > 
> > 您好，我这边是网站确实可以打开，但是演讲视频打不开，加载速度很慢，但是如果使用clash做代理的速度是够的，但是这个gfw规则列表好像是没有把ted的cdn域名放进列表
> 
> 因为ted本身就没有被墙，连接速度慢是因为国内运营商出口原因。可以手动设置分流。

好的，那我手动设置分流吧
