### ISSUE TITLE
steam图片无法正常显示

### ISSUE THREAD

**Issue by XMD0718** [Loukky/gfwlist-by-loukky#55]
设置为GFW列表模式时Steam展示的图片无法正常显示，而白名单模式则正常
![QQ截图20210225222430](https://user-images.githubusercontent.com/41297263/109167234-81c82f00-77b8-11eb-9398-1cf25d3a9f93.png)

**Comment by Loukky** [comment]
列表里面有steamcommunity.com这个域名在里面。这是我唯一能找到关联的，GFW列表模式我未使用过，也没有测试过。
所以无法给你提供建议。

**Comment by XMD0718** [comment]
该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题

**Comment by Loukky** [comment]
> 该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题

我测试图片是使用的七牛云的CDN

**Comment by XMD0718** [comment]
> > 该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题
> 
> 我测试图片是使用的七牛云的CDN

如果你那边测试的结果是图片走的七牛云CDN，那么可能是Steam的策略存在问题，错误判断了网络环境给了国外的CDN
刚才查了一下相关消息，发现这种情况还不少，网上给出的方法是在host文件里手动将这个域名指向靠近大陆的节点
另外我发现有部分Akamai CDN节点是被墙的，如果DNS解析这个域名的时候刚好解析到了被墙的IP，那么结果也是图片加载不出来
可考虑将此域名加入GFW列表

**Comment by Loukky** [comment]
> > > 该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题
> > 
> > 
> > 我测试图片是使用的七牛云的CDN
> 
> 如果你那边测试的结果是图片走的七牛云CDN，那么可能是Steam的策略存在问题，错误判断了网络环境给了国外的CDN
> 刚才查了一下相关消息，发现这种情况还不少，网上给出的方法是在host文件里手动将这个域名指向靠近大陆的节点
> 另外我发现有部分Akamai CDN节点是被墙的，如果DNS解析这个域名的时候刚好解析到了被墙的IP，那么结果也是图片加载不出来
> 可考虑将此域名加入GFW列表

更换DNS会不会改善该问题？

**Comment by XMD0718** [comment]
> > > > 该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题
> > > 
> > > 
> > > 我测试图片是使用的七牛云的CDN
> > 
> > 
> > 如果你那边测试的结果是图片走的七牛云CDN，那么可能是Steam的策略存在问题，错误判断了网络环境给了国外的CDN
> > 刚才查了一下相关消息，发现这种情况还不少，网上给出的方法是在host文件里手动将这个域名指向靠近大陆的节点
> > 另外我发现有部分Akamai CDN节点是被墙的，如果DNS解析这个域名的时候刚好解析到了被墙的IP，那么结果也是图片加载不出来
> > 可考虑将此域名加入GFW列表
> 
> 更换DNS会不会改善该问题？

我目前在软路由中已经使用了SmartDNS进行DNS结果优选，的确能够避免解析到被墙的IP，但是这个域名所提供的服务仍然很不稳定，大多数时候是能够加载部分图片，大部分图片记载不出来

**Comment by Loukky** [comment]
> > > > > 该问题似乎是由于Akamai CDN对国内部分网络环境不友好导致的，相关域名为cdn.akamai.steamstatic.com，此域名并未被墙，但国内连接至该域名提供的服务可能会出现不稳定的问题
> > > > 
> > > > 
> > > > 我测试图片是使用的七牛云的CDN
> > > 
> > > 
> > > 如果你那边测试的结果是图片走的七牛云CDN，那么可能是Steam的策略存在问题，错误判断了网络环境给了国外的CDN
> > > 刚才查了一下相关消息，发现这种情况还不少，网上给出的方法是在host文件里手动将这个域名指向靠近大陆的节点
> > > 另外我发现有部分Akamai CDN节点是被墙的，如果DNS解析这个域名的时候刚好解析到了被墙的IP，那么结果也是图片加载不出来
> > > 可考虑将此域名加入GFW列表
> > 
> > 
> > 更换DNS会不会改善该问题？
> 
> 我目前在软路由中已经使用了SmartDNS进行DNS结果优选，的确能够避免解析到被墙的IP，但是这个域名所提供的服务仍然很不稳定，大多数时候是能够加载部分图片，大部分图片记载不出来

需要更多观察该域名的情况

**Comment by XMD0718** [comment]
![QQ截图20210303020536](https://user-images.githubusercontent.com/41297263/109693779-06ee8200-7bc5-11eb-806e-1ef719773cce.png)
![QQ截图20210303020553](https://user-images.githubusercontent.com/41297263/109693796-0b1a9f80-7bc5-11eb-9543-9bcf739b30bf.png)

**Comment by Loukky** [comment]
https://mping.chinaz.com/?host=cdn.akamai.steamstatic.com
单独打开这个CDN域名会提示连接超时吗？

**Comment by XMD0718** [comment]
> 这是国内ping检测 https://mping.chinaz.com/?host=cdn.akamai.steamstatic.com
> 另外单独打开这个CDN域名会提示连接超时吗？

单独打开并不会，看样子只是提供图片存在问题

**Comment by Loukky** [comment]
> > 这是国内ping检测 https://mping.chinaz.com/?host=cdn.akamai.steamstatic.com
> > 另外单独打开这个CDN域名会提示连接超时吗？
> 
> 单独打开并不会，看样子只是提供图片存在问题

目前看来暂时没有办法认定该域名部分IP被阻断，另外你刚才贴的图片无法看到图片加载失败的原因。

**Comment by XMD0718** [comment]
https://www.17ce.com/site/http/20210303_db4052507b8311eba7135ba6f70ad643:1.html

可以看一下这个结果，我设置请求方式为Get，节点设置为仅路由器，ISP设置为仅移动联通电信，以模拟普通家宽访问的情况，可以看到有不少节点没有正常响应

我这边单独访问部分加载失败图片的链接结果是连接被重置，这个是原因

**Comment by Loukky** [comment]
> https://www.17ce.com/site/http/20210303_db4052507b8311eba7135ba6f70ad643:1.html
> 
> 可以看一下这个结果，我设置请求方式为Get，节点设置为仅路由器，ISP设置为仅移动联通电信，以模拟普通家宽访问的情况，可以看到有不少节点没有正常响应
> 
> 我这边单独访问部分加载失败图片的链接结果是连接被重置，这个是原因

我测试了其中连接失败的重庆移动节点dig获取的IP地址，发现可以连接。我更倾向于该节点问题。
该个问题我有空再多测试下看是被屏蔽还是当地ISP的原因。

**Comment by Loukky** [comment]
建议将上游DNS设为中科大

**Comment by XMD0718** [comment]
目前可以确认是节点对国内服务稳定性的问题，这其中有GFW的干扰，但域名本身并未被墙
