### ISSUE TITLE
Amazon Prime Video 和 Disney+ 流媒体相关域名

### ISSUE THREAD

**Issue by fluffyfoxxo** [Loukky/gfwlist-by-loukky#58]
既然 Netflix 相关域名在列表里，也许这两个流媒体也可以加上？
Prime Video:
- aiv-cdn.net
- aiv-cdn.net.c.footprint.net
- aiv-delivery.net
- amazonvideo.com
- atv-ext.amazon.com
- atv-ps.amazon.com
- media-amazon.com
- primevideo.com
- cloudfront.net（在测试中只发现 d25xi40x97liuc.cloudfront.net 和 dmqdd6hw24ucf.cloudfront.net 这两个二级域名）

Disney+:
- disney-plus.net
- disneyplus.com
- disneyplus.com.ssl.sc.omtrdc.net
- dssott.com
- dssott.com.akamaized.net
- bamgrid.com
- cdn.registerdisney.go.com
- cws.conviva.com
- braze.com

**Comment by Loukky** [comment]
已添加
