### ISSUE TITLE
static.wikia.nocookie.net疑似被SNI阻断了

### ISSUE THREAD

**Issue by Kithup2020** [Loukky/gfwlist-by-loukky#68]
打开[海外一个网站](https://evchk.wikia.org/zh/wiki/%E7%94%B0%E7%94%9F%E5%9C%B0%E7%94%A2#.E5.90.8D.E7.A8.B1.E8.A2.AB.E6.83.A1.E6.90.9E)，发现图片素材都无法载入
![截图1](https://user-images.githubusercontent.com/64726691/111860758-b6c53d00-8984-11eb-9b18-4a12874f174e.jpg)

排查后发现是下面这些网址出了问题：
https://static.wikia.nocookie.net/evchk/images/3/39/Tingsang_red4.jpg/revision/latest/scale-to-width-down/185?cb=20100923044959
https://static.wikia.nocookie.net/evchk/images/9/97/Question_book.svg/revision/latest/scale-to-width-down/50?cb=20080906123121
https://static.wikia.nocookie.net/evchk/images/4/43/Tingsang_red2.jpg/revision/latest/scale-to-width-down/139?cb=20100923045628

DNS对static.wikia.nocookie.net没有污染，对应IP的443端口也能通讯，但浏览器直接打开，发现都是秒弹“建立安全连接失败”的错误，与SNI阻断的症状高度相似，故建议static.wikia.nocookie.net加入列表。
![截图2](https://user-images.githubusercontent.com/64726691/111860848-305d2b00-8985-11eb-8103-826bb521f516.jpg)

**Comment by Kithup2020** [comment]
进一步抓包分析，RST就发生在TLS握手的CLIENT HELLO以后，而其中就包括了SNI信息“Server Name: static.wikia.nocookie.net”，极高度疑似是被SNI阻断了
![截图3](https://user-images.githubusercontent.com/64726691/111861566-44575b80-898a-11eb-9d86-4863c49ff184.jpg)

**Comment by Loukky** [comment]
本地测试可以正常显示，解析出来的DNS结果为FASTLY的CDN

**Comment by Kithup2020** [comment]
> 
> 
> 本地测试可以正常显示，解析出来的DNS结果为FASTLY的CDN

请问你本地是什么网络环境呢？我这边分别使用了中国电信和中国移动两个宽带网络环境测试，都复现了同一现象，才正式提交的

**Comment by Loukky** [comment]
> > 本地测试可以正常显示，解析出来的DNS结果为FASTLY的CDN
> 
> 请问你本地是什么网络环境呢？我这边分别使用了中国电信和中国移动两个宽带网络环境测试，都复现了同一现象，才正式提交的

联通宽带。上游DNS是中科大。
如果DNS是运营商的话，大概率会解析到74.120.190.194这个IP，这个IP似乎是wikia.com自家的，所以SNI阻断可能是针对该IP的。
151.101.192.194这个IP是我这里解析到的，你写到hosts文件试下，看还有阻断吗？

**Comment by Kithup2020** [comment]
谢谢指教！果然在Hosts把static.wikia.nocookie.net指定到151.101.192.194就可以直连访问了，也试过指定到其它151开头的系列IP也可以直连访问。看来SNI不只有针对域名的，还有针对特定IP的，这次长见识了，再次谢谢。
