### ISSUE TITLE
域名：tracker.m-team.cc，ping不通。

### ISSUE THREAD

**Issue by jackge0323** [Loukky/gfwlist-by-loukky#73]
ssr plus里添加直连似乎可解决，但是还是想从根本上解决，大佬请指教一下。

**Comment by Loukky** [comment]
ping不通也可能是服务器设置了禁ping的原因，不一定是被屏蔽了

**Comment by jackge0323** [comment]
因为是挂pt，全部黄种了，提示连不上服务器，经测试，如果添加此域名直连的话就可解决，如果不添加直连，就会ping不通，nslookup报错。

**Comment by Loukky** [comment]
该域名是正常的，使用的cloudflare的CDN

**Comment by jackge0323** [comment]
我又试了下，家里的台式机都一切正常，docker里的transmission容器，却ping不通，报bad address，如果ssr plus里设直连的话，docker的容器也能ping通，docker我用的host，这真是莫名奇妙的问题，我再研究研究，谢谢大佬。
