### ISSUE TITLE
please append

### ISSUE THREAD

**Issue by marcushsu** [Loukky/gfwlist-by-loukky#77]
All gov.tw cannot be accessed. All the items containing 'gov.tw' in the list must be whitelisted.

Some TW meida domain:
4gtv.tv
cnyes.com
udndata.com
mirrormedia.com.tw
businessweekly.com.tw
bnext.com.tw
commonhealth.com.tw
inside.com.tw
gamme.com.tw
ettoday.net
tvbs.com.tw
ithome.com.tw
gq.com.tw

Some Adult site:
jav777.cc
javfree.me
7mmtv.tv
m8008.com

**Comment by Loukky** [comment]
some gov.tw can access,like https://www.arte.gov.tw/ and https://www.aftygh.gov.tw/
and then , 
inside.com.tw
bnext.com.tw
mirrormedia.com.tw
udndata.com
cnyes.com
4gtv.tv
have add to the list,
other tw media domain can access .
and adult domain have add to the list

**Comment by marcushsu** [comment]
Thank you for your prompt update and reply. I still canno access the two gov.tw sites from my place, and, you can check www.aftygh.gov.tw, at lease, cannot be accessed from most cities in mainland China using the online tool https://tool.chinaz.com/speedtest/ .
For those sites you had added, they hadn't shown on my list. I will re-check them. Thank you again.

**Comment by marcushsu** [comment]
Hi, it's me again. I am sure that these URLs are blocked from my locations:
tvbs.com.tw
businessweekly.com.tw
and news.gamme.com.tw, at least.
![tvbs-1](https://user-images.githubusercontent.com/11764515/142363177-f856e649-e15c-4c34-bbea-5946f4c88ab9.png)
![bw-1](https://user-images.githubusercontent.com/11764515/142363212-f128484f-4465-469c-9b90-253ece349a85.png)
![gamme-1](https://user-images.githubusercontent.com/11764515/142363219-c69b033a-69ad-465d-9a91-cd998cf6aeaf.png)

**Comment by Loukky** [comment]
tvbs.com.tw can connet from CN.but the style.css domain cc.tvbs.com.tw has DNS cache pollution
businessweekly.com.tw and news.gamme.com.tw is add to the list now
