### ISSUE TITLE
可否改用其他地址存放gfwlist.txt

### ISSUE THREAD

**Issue by ldw710430** [Loukky/gfwlist-by-loukky#8]
默认的地址无法访问

比如可以放这：https://bitbucket.org/gfwlist/gfwlist/raw/HEAD/gfwlist.txt

**Comment by Loukky** [comment]
@ldw710430 暂时不会考虑，此项目主要是自己用。同时如果有人提issue需要添加也可以。

**Comment by BROBIRD** [comment]
https://cdn.jsdelivr.net/gh/Loukky/gfwlist-by-loukky@master/gfwlist.txt

**Comment by decentone** [comment]
自己做个反向代理就好了
