### ISSUE TITLE
please add some sites

### ISSUE THREAD

**Issue by marcushsu** [Loukky/gfwlist-by-loukky#84]
Please add some adult sites, image hosting, CDN blocked by gfw into the list. Thanks.

jdbstatic.com
jdbimgs.com
xoimg.com
ibb.co
imageshack.com
imgbox.com
pixhost.to
imagebam.com
netcdn.space
ccp.ovh
imagetwist.com
o--o.xyz
missav.com
netflav.com
tgbak.com
xxooen.com
tapecontent.net

**Comment by Loukky** [comment]
Only 2 domains can confirm DNS cache pollution by GFW.
Other domains need to post the links to confirm it blocked by GFW
