### ISSUE TITLE
*.storage.yandex.net

### ISSUE THREAD

**Issue by qwerttvv** [Loukky/gfwlist-by-loukky#87]
测试用链接如下，打开后随便下载个东西，地址*.storage.yandex.net用不了了，已经确认联通和移动都不行
https://disk.yandex.com/d/X0EVMKP4TcmnHQ

**Comment by Loukky** [comment]
我只抓到 https://downloader.disk.yandex.ru/ 这个地址 ,被 tcp reset了

**Comment by qwerttvv** [comment]
他是指向不同的服务器，前边前缀挺多的，我见到的不下10个，因为我老用这个网盘

**Comment by Loukky** [comment]
我测试没有发现 *.storage.yandex.net 这个域名,不过晚些时候我会添加上去

**Comment by qwerttvv** [comment]
https://s655sas.storage.yandex.net/rdisk/ce8455432937bee9b1a833adb7cd736062a45fd8a869d98694a4688da01c91ad/63694e72/CA4TuaTuB_g_eaxgcP7wASyPHXHzcHXSaoTpi0_3sMWz0MyW16aMdKBwr6AXj06wzWTJ3QcjcihL1h1sQzD5fA==?uid=0&filename=MpcVideoRenderer-0.6.2.1952_git2022.08.18-30ada65.zip&disposition=attachment&hash=CKPLBoe4QjFi3vuoOkHJwGpZla5bwh0dNO0wJtG/g4RqLHfeEvsP/Wjq5Shye0S2q/J6bpmRyOJonT3VoXnDag%3D%3D%3A/MpcVideoRenderer-0.6.2.1952_git2022.08.18-30ada65.zip&limit=0&content_type=application%2Fzip&owner_uid=4310091&fsize=734954&hid=8aa73b3a73babd53cf90794cc331968d&media_type=compressed&tknv=v2&rtoken=4WlB9VwtKVXU&force_default=no&ycrid=na-81e0327e5b28ad1e22bb1c13bc382f4f-downloader11e&ts=5ece5993b0080&s=5f45eca9c7ea576ded61cf605f6ef00614516a59ae1091c6e4aade99349b4d5d&pb=U2FsdGVkX1_t9NUMCXIeXqhPE3G6a9-yllgzz-ixAiWFDWlpHYPMr34NfaroI5eXC5pxvyFTuVf7oqoufC-i024OwsJr5z8EYrtgP1JPzac

**Comment by Loukky** [comment]
这个地址没有问题.

**Comment by qwerttvv** [comment]
行了：）
