### ISSUE TITLE
castbox.fm player.fm

### ISSUE THREAD

**Issue by ximalu** [Loukky/gfwlist-by-loukky#89]
播客类网站
castbox.fm
player.fm
podcast.app

**Comment by Loukky** [comment]
前面两个已经在列表里面了,最后一个已添加

**Comment by Loukky** [comment]
> 借楼反馈一下，这条规则会在SmartProxy中大面积错误杀https://github.com/salarcode/SmartProxy
> 
> ```
> /.*\/^https\?:\/\/\(platform|api|chat\)\.openai.com(?:[.?#\/].*)?$/
> ```
> 
> 还有，可以否将规则修改成https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format格式

请单独开个issue。另外原列表应该是
`/^https?:\/\/(platform|api|chat).openai.com`
你这个看起来似乎是转换出错了？
这是一条正则表达式，我在switxhyomega测试是没有问题，匹配特定子域

**Comment by Loukky** [comment]
> 扩展作者那边不怎么愿意修bug，以前反馈的东西都拒绝。 目前的情况误杀太严重了，很多网站都被判定，能否更新一下拆成三条规则？

改了下,我这里使用[SmartProxy](https://github.com/salarcode/SmartProxy)测试正常了
