### ISSUE TITLE
麻烦把m-team.cc移除 谢谢

### ISSUE THREAD

**Issue by wxg1015** [Loukky/gfwlist-by-loukky#93]
m-team.cc是一个bt站 一直用的二级域名作为站点域名 之前是pt.m-team.cc 被墙后马上换了kp.m-team.cc
但是现在把整个顶级域名都加入gfwlist会导致新的二级域名也走代理   作为一个pt站····这很麻烦···· 必须手动再把m-team.cc加到路由器的直连列表······  
鉴于以下因素，请求把m-team移出列表
1.pt站不能走代理 
2.如果被墙 运营者必然切换其另一个二级域名 代理顶级域名反而会导致新的二级域名也走代理了

**Comment by Loukky** [comment]
你担心的是哪一点，tracker走代理吗？
tracker的域名可以单独设置直连

**Comment by wxg1015** [comment]
> 你担心的是哪一点，tracker走代理吗？
> tracker的域名可以单独设置直连

嗯 对   我的意思是他在这个列表里没意义  因为作为pt站 他的网站域名必然也是需要可以直连的   因为并非每个pt玩家都翻墙的   按照之前墙的情况  都是墙的二级域名  上次是pt.m-team.cc   站长立马换用kp.m-team.cc(没被墙，可以直连) 就算是墙了顶级域名 必然也是弃用这个顶级域名 换用新的顶级域名  但是一旦把顶级域名加入gfw列表   就必须像你说的那样把tracker加入直连列表  这没啥意义  对于 不清楚状况的pt用户甚至会导致一直走了代理而不自知   毕竟一般观念里  玩pt/bt的话用gfw模式

**Comment by Loukky** [comment]
> > 你担心的是哪一点，tracker走代理吗？
> > tracker的域名可以单独设置直连
> 
> 嗯 对 我的意思是他在这个列表里没意义 因为作为pt站 他的网站域名必然也是需要可以直连的 因为并非每个pt玩家都翻墙的 按照之前墙的情况 都是墙的二级域名 上次是pt.m-team.cc 站长立马换用kp.m-team.cc(没被墙，可以直连) 就算是墙了顶级域名 必然也是弃用这个顶级域名 换用新的顶级域名 但是一旦把顶级域名加入gfw列表 就必须像你说的那样把tracker加入直连列表 这没啥意义 对于 不清楚状况的pt用户甚至会导致一直走了代理而不自知 毕竟一般观念里 玩pt/bt的话用gfw模式

PT下载的时候,域名只是通信用的,下载跟域名无关

**Comment by wxg1015** [comment]
> > > 你担心的是哪一点，tracker走代理吗？
> > > tracker的域名可以单独设置直连
> > 
> > 嗯 对 我的意思是他在这个列表里没意义 因为作为pt站 他的网站域名必然也是需要可以直连的 因为并非每个pt玩家都翻墙的 按照之前墙的情况 都是墙的二级域名 上次是pt.m-team.cc 站长立马换用kp.m-team.cc(没被墙，可以直连) 就算是墙了顶级域名 必然也是弃用这个顶级域名 换用新的顶级域名 但是一旦把顶级域名加入gfw列表 就必须像你说的那样把tracker加入直连列表 这没啥意义 对于 不清楚状况的pt用户甚至会导致一直走了代理而不自知 毕竟一般观念里 玩pt/bt的话用gfw模式
> 
> PT下载的时候,域名只是通信用的,下载跟域名无关

是啊  但是有些网站只记录连接tracker服务器所用的ip  如果走了代理 记录的就是代理的ip了 导致没上传  所以是上传的问题

**Comment by wxg1015** [comment]
简而言之 实际上这个域名被墙的只有pt.m-team.cc这个子域名  目前网站用的新的子域名 kp.m-team.cc tracker用的tracker.m-team.cc  都是可以直连的

**Comment by Loukky** [comment]
tracker.m-team.cc 我会加入直连规则
