### ISSUE TITLE
仓库的LICENSE是Apache-2.0，但是gfwlist.txt里的License是LGPL-2.1

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#97]
LGPL-2.1
`! License: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt`
应改为
Apache-2.0
`! License: https://www.apache.org/licenses/LICENSE-2.0.txt`
或将仓库LICENSE改为LGPL-2.1

**Comment by Loukky** [comment]
改成LGPL-2.1了
