### ISSUE TITLE
删除”403/451/520 & URL Redirects“部分的一些无效域名

### ISSUE THREAD

**Issue by hm9245** [Loukky/gfwlist-by-loukky#98]
删除解析不到（或已经关站）的域名：
athenaeizou.com
casinobellini.com
funkyimg.com
glass8.eu
lovetvshow.com
nr-data.net
intl.target.com
ulop.net
删除已恢复正常的域名：
bynet.co.il
clearsurance.com
monster.com
phmsociety.org
thebodyshop-usa.com
turntable.fm
zattoo.com
xfinity.com
vmpsoft.com
vevo.com
yandex.com
无法确定使用状态的域名：
nr-data.net

**Comment by Loukky** [comment]
aiv-cdn.net
aiv-cdn.net.c.footprint.net
aiv-delivery.net
这三个域名是迪士尼流媒体的相关子域名,且仍在使用.
nordstrommedia.com 
也有相关域名在使用
https://n.nordstrommedia.com/id/00950451-2f8d-47c4-a3da-361b839e7795.pdf
hautelookcdn.com
相关域名
https://www.hautelookcdn.com/resizer/434%C3%97650/products/MT7723R/large/6822232.jpg
wego.here.com 仍然是403
huluim.com 仍然有子域名在使用
omni7.jp 被DNS污染
media-amazon.com 似乎只是用来托管CSS与JS文件的.暂时先移除列表.
nr-data.net  似乎是因为disney解锁放进去,但我搜索到这个域名似乎使用于数据收集相关的.不过由于我没有disney plus无法具体测试.暂时先将其移除列表,后续有问题再反馈.参考这里 [https://support.opendns.com/hc/en-us/articles/360037591112-Domains-to-Allow-for-Disney-Plus](url)
uukanshu.com 国内ip访问会跳转到404页面

**有时候某个域名在列表里面.不代表这个域名就是被屏蔽的,有可能是其一个或多个子域名被污染的,这种情况也会将域名列入其中**

**Comment by hm9245** [comment]
感谢核对
但我用站长工具ping了一下omni7.jp。提示请求找不到主机
![站长工具检测结果](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/bbc46751-dded-4398-bdd6-7e00ab5b208a)
使用itdog的DNS查询功能（海外服务器），阿里DNS的检测结果
![阿里DNS查询结果](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/9de5ba24-a5eb-4de2-93b4-8e924bbfcea1)
谷歌DNS检测结果
![屏幕截图 2023-08-30 100543](https://github.com/Loukky/gfwlist-by-loukky/assets/141204703/edf772f7-4351-4f80-95ab-c1b4d8a8dce9)
阿里DNS部分服务器查询出IP地址，谷歌DNS没有记录
可能并不是DNS污染，暂时移除

**Comment by Loukky** [comment]
你试试 www.omni7.jp

**Comment by hm9245** [comment]
> 你试试 [www.omni7.jp](http://www.omni7.jp)

再次感谢，一次性检查太多域名没测清楚
